var request = { _eventListeners: 
   { finish: { handlers: null, flags: [Object] },
     peek: { handlers: null, flags: [Object] },
     disconnect: { handlers: null, flags: [Object] } },
  _notificationsQueue: [],
  _eventsProcessing: false,
  _sourcePodiums: [],
  _bench: { ts: 123540667.544501 },
  connection: 
   { _eventListeners: 
      { route: [Object],
        'request-internal': [Object],
        request: [Object],
        'request-error': [Object],
        response: [Object],
        tail: [Object] },
     _notificationsQueue: [],
     _eventsProcessing: true,
     _sourcePodiums: [ [Object], [Object] ],
     settings: 
      { compression: true,
        router: [Object],
        routes: [Object],
        host: 'localhost',
        port: 8080,
        labels: [],
        autoListen: true },
     server: 
      { _settings: [Object],
        _caches: [Object],
        _handlers: {},
        _methods: [Object],
        _events: [Object],
        _dependencies: [],
        _registrations: {},
        _heavy: [Object],
        _mime: [Object],
        _replier: [Object],
        _requestor: [Object],
        _decorations: {},
        _plugins: {},
        _app: {},
        _registring: false,
        _state: 'started',
        _extensionsSeq: 0,
        _extensions: [Object],
        _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: false,
        _sourcePodiums: [],
        _parent: null,
        root: [Circular],
        app: {},
        connections: [Object],
        load: [Object],
        methods: {},
        mime: [Object],
        plugins: {},
        settings: [Object],
        version: '16.1.0',
        realm: [Object],
        auth: [Object],
        info: [Object],
        listener: [Object],
        registrations: {} },
     type: 'tcp',
     _started: true,
     _connections: { '127.0.0.1:57035': [Object] },
     _onConnection: [Function],
     registrations: {},
     _extensions: 
      { onRequest: [Object],
        onPreAuth: [Object],
        onPostAuth: [Object],
        onPreHandler: [Object],
        onPostHandler: [Object],
        onPreResponse: [Object] },
     _requestCounter: { value: 10001, min: 10000, max: 99999 },
     _load: { _process: [Object], settings: [Object] },
     _compression: { encodings: [Object], _encoders: [Object], _decoders: [Object] },
     states: { settings: [Object], cookies: {}, names: [] },
     auth: 
      { connection: [Circular],
        _schemes: {},
        _strategies: {},
        settings: [Object],
        api: {} },
     _router: 
      { settings: [Object],
        routes: [Object],
        ids: {},
        vhosts: null,
        specials: [Object] },
     plugins: {},
     app: {},
     listener: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '4:127.0.0.1:8080' },
     info: 
      { created: 1485183845482,
        started: 1485183845493,
        host: 'localhost',
        port: 8080,
        protocol: 'http',
        id: 'mwheeler-ae2ee8:97401:iya845ey',
        uri: 'http://localhost:8080',
        address: '127.0.0.1' } },
  server: 
   { _settings: 
      { debug: [Object],
        load: [Object],
        mime: null,
        useDomains: true,
        connections: [Object] },
     _caches: { _default: [Object] },
     _handlers: {},
     _methods: { server: [Circular], methods: {}, _normalized: {} },
     _events: 
      { _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: false,
        _sourcePodiums: [Object] },
     _dependencies: [],
     _registrations: {},
     _heavy: 
      { settings: [Object],
        _eventLoopTimer: null,
        _loadBench: [Object],
        load: [Object] },
     _mime: Mimos { _byType: [Object], _byExtension: [Object] },
     _replier: { _decorations: null },
     _requestor: { _decorations: null },
     _decorations: {},
     _plugins: {},
     _app: {},
     _registring: false,
     _state: 'started',
     _extensionsSeq: 0,
     _extensions: 
      { onPreStart: [Object],
        onPostStart: [Object],
        onPreStop: [Object],
        onPostStop: [Object] },
     _eventListeners: 
      { route: [Object],
        'request-internal': [Object],
        request: [Object],
        'request-error': [Object],
        response: [Object],
        tail: [Object],
        log: [Object],
        start: [Object],
        stop: [Object] },
     _notificationsQueue: [],
     _eventsProcessing: false,
     _sourcePodiums: [],
     _parent: null,
     root: [Circular],
     app: {},
     connections: [ [Object] ],
     load: { eventLoopDelay: 0, heapUsed: 0, rss: 0 },
     methods: {},
     mime: Mimos { _byType: [Object], _byExtension: [Object] },
     plugins: {},
     settings: 
      { debug: [Object],
        load: [Object],
        mime: null,
        useDomains: true,
        connections: [Object] },
     version: '16.1.0',
     realm: 
      { _extensions: [Object],
        modifiers: [Object],
        plugin: '',
        pluginOptions: {},
        plugins: {},
        settings: [Object] },
     auth: 
      { default: [Function: default],
        scheme: [Function: scheme],
        strategy: [Function: strategy],
        test: [Function: test],
        api: {} },
     info: 
      { created: 1485183845482,
        started: 1485183845493,
        host: 'localhost',
        port: 8080,
        protocol: 'http',
        id: 'mwheeler-ae2ee8:97401:iya845ey',
        uri: 'http://localhost:8080',
        address: '127.0.0.1' },
     listener: 
      Server {
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _connections: 1,
        _handle: [Object],
        _usingSlaves: false,
        _slaves: [],
        _unref: false,
        allowHalfOpen: true,
        pauseOnConnect: false,
        httpAllowHalfOpen: false,
        timeout: 120000,
        _pendingResponseData: 0,
        _connectionKey: '4:127.0.0.1:8080' },
     registrations: {} },
  url: 
   Url {
     protocol: null,
     slashes: null,
     auth: null,
     host: null,
     port: null,
     hostname: null,
     hash: null,
     search: '',
     query: {},
     pathname: '/testing',
     path: '/testing',
     href: '/testing' },
  query: {},
  path: '/testing',
  method: 'get',
  mime: null,
  setUrl: undefined,
  setMethod: undefined,
  headers: 
   { host: 'localhost:8080',
     connection: 'keep-alive',
     'cache-control': 'max-age=0',
     'upgrade-insecure-requests': '1',
     'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36',
     accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
     dnt: '1',
     'accept-encoding': 'gzip, deflate, sdch, br',
     'accept-language': 'en-US,en;q=0.8',
     cookie: 'BMAP_device=highResolutionDisplay%2Cbrowser' },
  id: '1485183855298:mwheeler-ae2ee8:97401:iya845ey:10000',
  app: {},
  plugins: {},
  _route: 
   { settings: 
      { cache: [Object],
        compression: {},
        cors: false,
        files: [Object],
        json: [Object],
        log: false,
        payload: null,
        response: [Object],
        security: null,
        state: [Object],
        timeout: [Object],
        validate: [Object],
        ext: {},
        handler: [Function: handler],
        vhost: undefined,
        plugins: {},
        app: {},
        auth: undefined },
     connection: 
      { _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: true,
        _sourcePodiums: [Object],
        settings: [Object],
        server: [Object],
        type: 'tcp',
        _started: true,
        _connections: [Object],
        _onConnection: [Function],
        registrations: {},
        _extensions: [Object],
        _requestCounter: [Object],
        _load: [Object],
        _compression: [Object],
        states: [Object],
        auth: [Object],
        _router: [Object],
        plugins: {},
        app: {},
        listener: [Object],
        info: [Object] },
     server: 
      { _settings: [Object],
        _caches: [Object],
        _handlers: {},
        _methods: [Object],
        _events: [Object],
        _dependencies: [],
        _registrations: {},
        _heavy: [Object],
        _mime: [Object],
        _replier: [Object],
        _requestor: [Object],
        _decorations: {},
        _plugins: {},
        _app: {},
        _registring: false,
        _state: 'started',
        _extensionsSeq: 0,
        _extensions: [Object],
        _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: false,
        _sourcePodiums: [],
        _parent: null,
        root: [Circular],
        app: {},
        connections: [Object],
        load: [Object],
        methods: {},
        mime: [Object],
        plugins: {},
        settings: [Object],
        version: '16.1.0',
        realm: [Object],
        auth: [Object],
        info: [Object],
        listener: [Object],
        registrations: {} },
     path: '/{name}',
     method: 'get',
     plugin: 
      { _settings: [Object],
        _caches: [Object],
        _handlers: {},
        _methods: [Object],
        _events: [Object],
        _dependencies: [],
        _registrations: {},
        _heavy: [Object],
        _mime: [Object],
        _replier: [Object],
        _requestor: [Object],
        _decorations: {},
        _plugins: {},
        _app: {},
        _registring: false,
        _state: 'started',
        _extensionsSeq: 0,
        _extensions: [Object],
        _eventListeners: [Object],
        _notificationsQueue: [],
        _eventsProcessing: false,
        _sourcePodiums: [],
        _parent: null,
        root: [Circular],
        app: {},
        connections: [Object],
        load: [Object],
        methods: {},
        mime: [Object],
        plugins: {},
        settings: [Object],
        version: '16.1.0',
        realm: [Object],
        auth: [Object],
        info: [Object],
        listener: [Object],
        registrations: {} },
     _special: false,
     _analysis: { segments: [Object], fingerprint: '/?', params: [Object] },
     params: [ 'name' ],
     fingerprint: '/?',
     public: 
      { method: 'get',
        path: '/{name}',
        vhost: undefined,
        realm: [Object],
        settings: [Object],
        fingerprint: '/?',
        auth: [Object] },
     _prerequisites: null,
     _extensions: 
      { onPreResponse: [Object],
        onPreAuth: [Object],
        onPostAuth: [Object],
        onPreHandler: [Object],
        onPostHandler: [Object] },
     _cycle: [ [Function], [Function], [Function] ] },
  route: 
   { method: 'get',
     path: '/{name}',
     vhost: undefined,
     realm: 
      { _extensions: [Object],
        modifiers: [Object],
        plugin: '',
        pluginOptions: {},
        plugins: {},
        settings: [Object] },
     settings: 
      { cache: [Object],
        compression: {},
        cors: false,
        files: [Object],
        json: [Object],
        log: false,
        payload: null,
        response: [Object],
        security: null,
        state: [Object],
        timeout: [Object],
        validate: [Object],
        ext: {},
        handler: [Function: handler],
        vhost: undefined,
        plugins: {},
        app: {},
        auth: undefined },
     fingerprint: '/?',
     auth: { access: [Function: access] } },
  auth: 
   { isAuthenticated: false,
     credentials: null,
     artifacts: null,
     strategy: null,
     mode: null,
     error: null },
  pre: {},
  preResponses: {},
  info: 
   { received: 1485183855298,
     responded: 0,
     remoteAddress: '127.0.0.1',
     remotePort: 57035,
     referrer: '',
     host: 'localhost:8080',
     acceptEncoding: 'gzip',
     hostname: 'localhost' },
  orig: {},
  params: { name: 'testing' },
  paramsArray: [ 'testing' ],
  payload: null,
  state: { BMAP_device: 'highResolutionDisplay%2Cbrowser' },
  jsonp: null,
  response: null,
  raw: 
   { req: 
      IncomingMessage {
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: false,
        headers: [Object],
        rawHeaders: [Object],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '/testing',
        method: 'GET',
        statusCode: null,
        statusMessage: null,
        client: [Object],
        _consuming: false,
        _dumped: false },
     res: 
      ServerResponse {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedHeader: {},
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Object],
        connection: [Object],
        _header: null,
        _headers: null,
        _headerNames: {},
        _onPendingData: [Function: updateOutgoingData] } },
  addTail: [Function],
  tail: [Function],
  _states: {},
  _entity: {},
  _logger: [],
  _allowInternals: false,
  _isPayloadPending: true,
  _isBailed: false,
  _isReplied: false,
  _isFinalized: false,
  _tails: {},
  _tailIds: 0,
  _protect: 
   { _error: [Function],
     logger: [Circular],
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [] } },
  domain: 
   Domain {
     domain: null,
     _events: { error: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     members: [] },
  _onEnd: [Function],
  _onClose: [Function],
  _onError: [Function] }

